#Makefile
include .env

#run main program
run:
	@go run ./cmd/main.go

#testing
test:
	@go test ./tests

#database commands
up:
	@echo migrating up
	cd ./migrations && goose ${GOOSE_DRIVER} ${DB_URL} up

down:
	@echo migrating down
	cd ./migrations && goose ${GOOSE_DRIVER} ${DB_URL} down
