#Makefile
include .env

run:
	@go run ./cmd/main.go

#database commands
up:
	@echo migrating up
	cd ./migrations && goose ${GOOSE_DRIVER} ${DB_URL} up

down:
	@echo migrating down
	cd ./migrations && goose ${GOOSE_DRIVER} ${DB_URL} down
